# Revision - Level 1 - 20/04/2026
- Revision about the starting fundamentals of handling Null/NaN values

In [2]:
import pandas as pd

## Nível 1 — Fundamentos (1–4)

## ⚔️ 1.

Mostre:

👉 quantos valores nulos existem em cada coluna

In [3]:
df = pd.read_csv("weather_data.csv")
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [6]:
df.isna().sum()

day            0
temperature    4
windspeed      4
event          2
dtype: int64

## ⚔️ 2.

Mostre:

👉 apenas as linhas que possuem pelo menos 1 valor nulo

In [13]:
df[df.isnull().any(axis=1)]

        day  temperature  windspeed  event
1  1/4/2017          NaN        9.0  Sunny
2  1/5/2017         28.0        NaN   Snow
3  1/6/2017          NaN        7.0    NaN
4  1/7/2017         32.0        NaN   Rain
5  1/8/2017          NaN        NaN  Sunny
6  1/9/2017          NaN        NaN    NaN

## ⚔️ 3.

Mostre:

👉 apenas as linhas onde temperature está nulo

In [16]:
df[df.temperature.isnull()]

        day  temperature  windspeed  event
1  1/4/2017          NaN        9.0  Sunny
3  1/6/2017          NaN        7.0    NaN
5  1/8/2017          NaN        NaN  Sunny
6  1/9/2017          NaN        NaN    NaN

## ⚔️ 4.

Descubra:

👉 quantos valores nulos existem no dataset inteiro

In [24]:
df.isnull().sum().sum()

np.int64(10)

## Nível 2 — Preenchimento (5–7)

## ⚔️ 5.

Preencha os valores nulos de:

- temperature com 0
- windspeed com 0
- event com "No Event"

👉 (sem alterar o df original)

In [33]:
df_copy = df.copy()

In [27]:
df_copy.fillna({
    'temperature': 0,
    'windspeed': 0,
    'event': "No Event"
}, inplace=True)
df_copy

         day  temperature  windspeed     event
0   1/1/2017         32.0        6.0      Rain
1   1/4/2017          0.0        9.0     Sunny
2   1/5/2017         28.0        0.0      Snow
3   1/6/2017          0.0        7.0  No Event
4   1/7/2017         32.0        0.0      Rain
5   1/8/2017          0.0        0.0     Sunny
6   1/9/2017          0.0        0.0  No Event
7  1/10/2017         34.1        8.1    Cloudy
8  1/11/2017         40.0       12.0     Sunny

## ⚔️ 6.

Preencha os valores nulos de:

👉 temperature com a média da coluna

In [31]:
df_copy.fillna({
    'temperature': df.temperature.mean()
}, inplace=True)
df_copy

         day  temperature  windspeed   event
0   1/1/2017        32.00        6.0    Rain
1   1/4/2017        33.22        9.0   Sunny
2   1/5/2017        28.00        NaN    Snow
3   1/6/2017        33.22        7.0     NaN
4   1/7/2017        32.00        NaN    Rain
5   1/8/2017        33.22        NaN   Sunny
6   1/9/2017        33.22        NaN     NaN
7  1/10/2017        34.10        8.1  Cloudy
8  1/11/2017        40.00       12.0   Sunny

## ⚔️ 7.

Preencha os valores nulos usando:

👉 o valor anterior (forward fill)

In [32]:
df_copy.ffill()

         day  temperature  windspeed   event
0   1/1/2017        32.00        6.0    Rain
1   1/4/2017        33.22        9.0   Sunny
2   1/5/2017        28.00        9.0    Snow
3   1/6/2017        33.22        7.0    Snow
4   1/7/2017        32.00        7.0    Rain
5   1/8/2017        33.22        7.0   Sunny
6   1/9/2017        33.22        7.0   Sunny
7  1/10/2017        34.10        8.1  Cloudy
8  1/11/2017        40.00       12.0   Sunny

## Nível 3 — Manipulação mais esperta (8–10)

## ⚔️ 8.

Preencha os valores nulos usando:

👉 o valor seguinte (backfill)

In [34]:
df_copy.bfill()

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017         28.0        9.0   Sunny
2   1/5/2017         28.0        7.0    Snow
3   1/6/2017         32.0        7.0    Rain
4   1/7/2017         32.0        8.1    Rain
5   1/8/2017         34.1        8.1   Sunny
6   1/9/2017         34.1        8.1  Cloudy
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

## ⚔️ 9.

Remova:

👉 linhas onde TODOS os valores são nulos

In [38]:
df_copy = pd.read_csv("weather_data.csv", parse_dates=['day'])
df_copy.set_index('day', inplace=True)
df_copy.dropna(how='all', inplace=True)
df_copy

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

## ⚔️ 10.

Remova:

👉 linhas que tenham menos de 2 valores preenchidos

In [46]:
df_copy = df.copy()
df_copy.dropna(thresh=2, inplace=True)
df_copy

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

## ⚔️ 11.

Tente usar:

👉 interpolate()

In [50]:
df2 = df[['temperature', 'windspeed']]
df2.interpolate()

   temperature  windspeed
0         32.0      6.000
1         30.0      9.000
2         28.0      8.000
3         30.0      7.000
4         32.0      7.275
5         32.7      7.550
6         33.4      7.825
7         34.1      8.100
8         40.0     12.000