# Revision - Level 2 - 21/04/2026
- Revision about handling Null/NaN

## ⚔️ MISSÃO 1 — Diagnóstico completo

Antes de mexer em qualquer coisa:

👉 Descubra:
- Quantos valores nulos existem por coluna  
- Qual coluna tem mais problemas  
- Existe linha totalmente vazia?  

👉 **Entrega:**
- Resposta + pequena interpretação

In [53]:
import pandas as pd

In [54]:
df = pd.read_csv("store_sales_weather.csv", parse_dates=['date'])
df

,date,store,product_category,units_sold,price,temperature,rain_mm,promo,holiday
0,2026-04-01,North,Electronics,15.0,1200.0,28.0,0.0,Yes,No
1,2026-04-02,North,Electronics,NaN,1200.0,29.0,2.0,Yes,No
2,2026-04-03,North,Groceries,120.0,8.0,27.0,15.0,No,No
3,2026-04-04,North,Groceries,130.0,8.0,NaN,20.0,No,No
4,2026-04-05,North,Clothing,25.0,80.0,26.0,NaN,Yes,No
5,2026-04-06,North,Clothing,NaN,80.0,25.0,5.0,NaN,No
6,2026-04-07,North,Electronics,10.0,NaN,24.0,0.0,No,No
7,2026-04-08,South,Electronics,18.0,1150.0,30.0,0.0,Yes,No
8,2026-04-09,South,Groceries,140.0,7.5,31.0,NaN,No,No
9,2026-04-10,South,Groceries,NaN,7.5,32.0,0.0,No,No
10,2026-04-11,South,Clothing,20.0,75.0,NaN,12.0,Yes,No
11,2026-04-12,South,Clothing,22.0,75.0,29.0,8.0,Yes,NaN
12,2026-04-13,South,Electronics,12.0,1150.0,28.0,0.0,No,No
13,2026-04-14,South,Electronics,NaN,1150.0,27.0,0.0,No,No
14,2026-04-15,East,Groceries,150.0,7.0,33.0,0.0,Yes,No
15,2026-04-16,East,Groceries,155.0,7.0,NaN,0.0,Yes,No
16,2026-04-17,East,Clothing,30.0,70.0,31.0,25.0,No,No
17,2026-04-18,East,Clothing,NaN,70.0,30.0,30.0,No,No
18,2026-04-19,East,Electronics,9.0,1100.0,29.0,NaN,No,No
19,2026-04-20,East,Electronics,8.0,NaN,28.0,0.0,No,No
20,2026-04-21,West,Groceries,160.0,6.8,34.0,0.0,Yes,No
21,2026-04-22,West,Groceries,NaN,6.8,35.0,0.0,Yes,No
22,2026-04-23,West,Clothing,28.0,72.0,33.0,18.0,No,No
23,2026-04-24,West,Clothing,26.0,72.0,NaN,22.0,No,No
24,2026-04-25,West,Electronics,11.0,1080.0,30.0,0.0,NaN,No
25,2026-04-26,West,Electronics,10.0,1080.0,29.0,0.0,No,No
26,2026-04-27,West,Groceries,NaN,NaN,32.0,5.0,No,No
27,2026-04-28,North,Groceries,125.0,8.0,27.0,10.0,No,No
28,2026-04-29,South,Clothing,21.0,75.0,28.0,NaN,Yes,No
29,2026-04-30,East,Electronics,10.0,1100.0,27.0,0.0,No,No

In [55]:
df.shape

(30, 9)

In [56]:
df.dtypes

date                datetime64[us]
store                          str
product_category               str
units_sold                 float64
price                      float64
temperature                float64
rain_mm                    float64
promo                          str
holiday                        str
dtype: object

In [57]:
df.isna().sum()

date                0
store               0
product_category    0
units_sold          7
price               3
temperature         4
rain_mm             4
promo               2
holiday             1
dtype: int64

In [58]:
df.isna().sum().sum()

np.int64(21)

**Answers**
1. we have per column:
   - `units_sold`: 7 NaN
   - `price`: 3 NaN
   - `temperature`: 4 NaN
   - `rain_mm`: 4 NaN
   - `promo`: 2 NaN
   - `holiday`: 1 NaN
   **Total:** 21 NaN

2. The column `units_sold` has more null values

3. There are no rows that has only null values

## ⚔️ MISSÃO 2 — Classificação das colunas

Classifique cada coluna em:

- Numérica contínua  
- Numérica operacional  
- Categórica  

👉 Exemplo:
- temperature → ?  
- units_sold → ?  

👉 **Entrega:**
- Lista com justificativa

In [59]:
df.head(4)

,date,store,product_category,units_sold,price,temperature,rain_mm,promo,holiday
0,2026-04-01,North,Electronics,15.0,1200.0,28.0,0.0,Yes,No
1,2026-04-02,North,Electronics,NaN,1200.0,29.0,2.0,Yes,No
2,2026-04-03,North,Groceries,120.0,8.0,27.0,15.0,No,No
3,2026-04-04,North,Groceries,130.0,8.0,NaN,20.0,No,No

In [82]:
dictionary = {
    'date': 'Temporal',
    'store': 'Categórica',
    'product_category': 'Categórica',
    'units_sold': 'Numérica Operacional',
    'price': 'Numérica Contínua',
    'temperature': 'Numérica Contínua',
    'rain_mm': 'Numérica Contínua',
    'promo': 'Categórica',
    'holiday': 'Categórica'
}

The way the columns were categorized are:

- Continuous Numeric: values that can have an infinite range, such as `price`, `temperature`, `rain_mm`
- Operacional Numeric: values thar are based on mathematical results, such as `units_sold`
- Categoric: values that represent categorized values, such as `store`, `product_category`, `promo`, `holiday`

## ⚔️ MISSÃO 3 — Estratégia por coluna (ESSENCIAL)

Para cada coluna com NA, decida:

👉 O que fazer?

Escolhas possíveis:
- Preencher com média  
- Interpolar  
- Forward fill  
- Backfill  
- Manter nulo  
- Remover  

👉 **Entrega:**
- Estratégia + justificativa

In [61]:
df

,date,store,product_category,units_sold,price,temperature,rain_mm,promo,holiday
0,2026-04-01,North,Electronics,15.0,1200.0,28.0,0.0,Yes,No
1,2026-04-02,North,Electronics,NaN,1200.0,29.0,2.0,Yes,No
2,2026-04-03,North,Groceries,120.0,8.0,27.0,15.0,No,No
3,2026-04-04,North,Groceries,130.0,8.0,NaN,20.0,No,No
4,2026-04-05,North,Clothing,25.0,80.0,26.0,NaN,Yes,No
5,2026-04-06,North,Clothing,NaN,80.0,25.0,5.0,NaN,No
6,2026-04-07,North,Electronics,10.0,NaN,24.0,0.0,No,No
7,2026-04-08,South,Electronics,18.0,1150.0,30.0,0.0,Yes,No
8,2026-04-09,South,Groceries,140.0,7.5,31.0,NaN,No,No
9,2026-04-10,South,Groceries,NaN,7.5,32.0,0.0,No,No
10,2026-04-11,South,Clothing,20.0,75.0,NaN,12.0,Yes,No
11,2026-04-12,South,Clothing,22.0,75.0,29.0,8.0,Yes,NaN
12,2026-04-13,South,Electronics,12.0,1150.0,28.0,0.0,No,No
13,2026-04-14,South,Electronics,NaN,1150.0,27.0,0.0,No,No
14,2026-04-15,East,Groceries,150.0,7.0,33.0,0.0,Yes,No
15,2026-04-16,East,Groceries,155.0,7.0,NaN,0.0,Yes,No
16,2026-04-17,East,Clothing,30.0,70.0,31.0,25.0,No,No
17,2026-04-18,East,Clothing,NaN,70.0,30.0,30.0,No,No
18,2026-04-19,East,Electronics,9.0,1100.0,29.0,NaN,No,No
19,2026-04-20,East,Electronics,8.0,NaN,28.0,0.0,No,No
20,2026-04-21,West,Groceries,160.0,6.8,34.0,0.0,Yes,No
21,2026-04-22,West,Groceries,NaN,6.8,35.0,0.0,Yes,No
22,2026-04-23,West,Clothing,28.0,72.0,33.0,18.0,No,No
23,2026-04-24,West,Clothing,26.0,72.0,NaN,22.0,No,No
24,2026-04-25,West,Electronics,11.0,1080.0,30.0,0.0,NaN,No
25,2026-04-26,West,Electronics,10.0,1080.0,29.0,0.0,No,No
26,2026-04-27,West,Groceries,NaN,NaN,32.0,5.0,No,No
27,2026-04-28,North,Groceries,125.0,8.0,27.0,10.0,No,No
28,2026-04-29,South,Clothing,21.0,75.0,28.0,NaN,Yes,No
29,2026-04-30,East,Electronics,10.0,1100.0,27.0,0.0,No,No

In this case I used multiple methods for fill na values on the Dataframe, 

I interpolate on values from columns: `units_sold` and `price`, that way the result would not create a possible outlier or when doing the mean or median, the values would still follow a pattern.

For the `temperature` and `rain_mm` I used the .fillna() and calculated the mean(), that way both would be values that are similarly close to other values.

For `promo` I used .ffill() but if we had another column that could explain it when do we consider a promo or note we could have filled with real values

For `holiday` i used the bfill(), but similarly from the case before, we could check if that row date is a holiday or not so that way we could have replaced the null values for real world values, the problem is that I do not know what country those days are based on

## ⚔️ MISSÃO 4 — Aplicação controlada

Agora sim:

👉 Aplique suas decisões  

**Regras:**
- Não alterar o dataset original  
- Criar uma versão limpa  

👉 **Entrega:**
- DataFrame limpo

In [62]:
# Fill na by interpolation
df_clean = df.copy()
df_clean.units_sold = df_clean.units_sold.interpolate()
df_clean.price = df_clean.price.interpolate()

# Fill na by ffill
df_clean.promo = df_clean.promo.ffill()

# Fill na by bfill
df_clean.holiday = df_clean.holiday.bfill()

# Fill na by using fillna with mean()
df_clean = df_clean.fillna({
    'temperature': df_clean.temperature.mean(),
    'rain_mm': df_clean.rain_mm.mean()
})

df_clean = df_clean.round({
    'units_sold': 1, 
    'price': 1, 
    'temperature': 1, 
    'rain_mm': 1
})

df_clean

,date,store,product_category,units_sold,price,temperature,rain_mm,promo,holiday
0,2026-04-01,North,Electronics,15.0,1200.0,28.0,0.0,Yes,No
1,2026-04-02,North,Electronics,67.5,1200.0,29.0,2.0,Yes,No
2,2026-04-03,North,Groceries,120.0,8.0,27.0,15.0,No,No
3,2026-04-04,North,Groceries,130.0,8.0,29.3,20.0,No,No
4,2026-04-05,North,Clothing,25.0,80.0,26.0,6.6,Yes,No
5,2026-04-06,North,Clothing,17.5,80.0,25.0,5.0,Yes,No
6,2026-04-07,North,Electronics,10.0,615.0,24.0,0.0,No,No
7,2026-04-08,South,Electronics,18.0,1150.0,30.0,0.0,Yes,No
8,2026-04-09,South,Groceries,140.0,7.5,31.0,6.6,No,No
9,2026-04-10,South,Groceries,80.0,7.5,32.0,0.0,No,No
10,2026-04-11,South,Clothing,20.0,75.0,29.3,12.0,Yes,No
11,2026-04-12,South,Clothing,22.0,75.0,29.0,8.0,Yes,No
12,2026-04-13,South,Electronics,12.0,1150.0,28.0,0.0,No,No
13,2026-04-14,South,Electronics,81.0,1150.0,27.0,0.0,No,No
14,2026-04-15,East,Groceries,150.0,7.0,33.0,0.0,Yes,No
15,2026-04-16,East,Groceries,155.0,7.0,29.3,0.0,Yes,No
16,2026-04-17,East,Clothing,30.0,70.0,31.0,25.0,No,No
17,2026-04-18,East,Clothing,19.5,70.0,30.0,30.0,No,No
18,2026-04-19,East,Electronics,9.0,1100.0,29.0,6.6,No,No
19,2026-04-20,East,Electronics,8.0,553.4,28.0,0.0,No,No
20,2026-04-21,West,Groceries,160.0,6.8,34.0,0.0,Yes,No
21,2026-04-22,West,Groceries,94.0,6.8,35.0,0.0,Yes,No
22,2026-04-23,West,Clothing,28.0,72.0,33.0,18.0,No,No
23,2026-04-24,West,Clothing,26.0,72.0,29.3,22.0,No,No
24,2026-04-25,West,Electronics,11.0,1080.0,30.0,0.0,No,No
25,2026-04-26,West,Electronics,10.0,1080.0,29.0,0.0,No,No
26,2026-04-27,West,Groceries,67.5,544.0,32.0,5.0,No,No
27,2026-04-28,North,Groceries,125.0,8.0,27.0,10.0,No,No
28,2026-04-29,South,Clothing,21.0,75.0,28.0,6.6,Yes,No
29,2026-04-30,East,Electronics,10.0,1100.0,27.0,0.0,No,No

## ⚔️ MISSÃO 5 — Impacto da limpeza

Compare:

- Antes vs depois  

👉 Perguntas:
- Quantos NA restaram?  
- Algum comportamento estranho apareceu?  

👉 **Entrega:**
- Comparação + observações

No NAs remaining, all were trecked and deatl with.

The biggest problem that appeared is the fact that rain_mm was populated with most 0.0 values, of course it makes sense if no rain happend that day, but if it happend and the value is 0.0 we may have a problem with future analysis

## ⚔️ MISSÃO 6 — Casos críticos

Analise especificamente:

👉 `units_sold`

👉 Pergunta:
- Faz sentido preencher?  
- Ou isso pode distorcer análise?  

👉 **Entrega:**
- Decisão + justificativa

I do think that the analysis may be wrong if we handle hte null value from the `units_sold` column, using interpolation was a prevenitve method, because, we can have a small number of products that are sold resulting on higher prices, so that way future analysis can become bias.

## ⚔️ MISSÃO 7 — Análise com dados limpos

Agora usa o dataset limpo:

👉 Descubra:
- Média de vendas por categoria  
- Média de preço por loja  

👉 **Entrega:**
- Resultados + breve interpretação

In [63]:
df.head(3)

,date,store,product_category,units_sold,price,temperature,rain_mm,promo,holiday
0,2026-04-01,North,Electronics,15.0,1200.0,28.0,0.0,Yes,No
1,2026-04-02,North,Electronics,NaN,1200.0,29.0,2.0,Yes,No
2,2026-04-03,North,Groceries,120.0,8.0,27.0,15.0,No,No

In [65]:
df_clean.groupby('product_category')['units_sold'].mean().round(2)

product_category
Clothing        23.22
Electronics     22.86
Groceries      122.15
Name: units_sold, dtype: float64

In [67]:
df_clean.groupby('store')['price'].mean().round(2)

store
East     415.34
North    399.88
South    461.25
West     408.80
Name: price, dtype: float64

We have that by products category Groceries are the higher value, which make sense since Groceries are any food and hygiene products related.

And by the store, we have that South store have a higher mean(), but this is not concusive since we are using the cleaned dataset, and the NaN treated values can interfere with this result

## ⚔️ MISSÃO 8 — Insight com contexto externo

Use:

- `rain_mm`  
- `temperature`  

👉 Pergunta:

Dias com chuva impactam vendas?

👉 **Entrega:**
- Análise + conclusão

In [78]:
df_clean.groupby('rain_mm').agg({
    'units_sold': 'sum',
    'price': 'sum'
})

         units_sold   price
rain_mm
0.0           814.0  9113.5
2.0            67.5  1200.0
5.0            85.0   624.0
6.6           195.0  1262.5
8.0            22.0    75.0
10.0          125.0     8.0
12.0           20.0    75.0
15.0          120.0     8.0
18.0           28.0    72.0
20.0          130.0     8.0
22.0           26.0    72.0
25.0           30.0    70.0
30.0           19.5    70.0

Inconclusive, if we see the analysis, we have that days that did not ocurred rain have sold more, the motive is inconclusive, is because during the cleaning by using mean(), we added more values to the 0.0 category, we will see if we drop this na values if we have the same thing

In [80]:
df_no_na = df.copy()
df_no_na = df_no_na.dropna(subset=['rain_mm'])
df_no_na

,date,store,product_category,units_sold,price,temperature,rain_mm,promo,holiday
0,2026-04-01,North,Electronics,15.0,1200.0,28.0,0.0,Yes,No
1,2026-04-02,North,Electronics,NaN,1200.0,29.0,2.0,Yes,No
2,2026-04-03,North,Groceries,120.0,8.0,27.0,15.0,No,No
3,2026-04-04,North,Groceries,130.0,8.0,NaN,20.0,No,No
5,2026-04-06,North,Clothing,NaN,80.0,25.0,5.0,NaN,No
6,2026-04-07,North,Electronics,10.0,NaN,24.0,0.0,No,No
7,2026-04-08,South,Electronics,18.0,1150.0,30.0,0.0,Yes,No
9,2026-04-10,South,Groceries,NaN,7.5,32.0,0.0,No,No
10,2026-04-11,South,Clothing,20.0,75.0,NaN,12.0,Yes,No
11,2026-04-12,South,Clothing,22.0,75.0,29.0,8.0,Yes,NaN
12,2026-04-13,South,Electronics,12.0,1150.0,28.0,0.0,No,No
13,2026-04-14,South,Electronics,NaN,1150.0,27.0,0.0,No,No
14,2026-04-15,East,Groceries,150.0,7.0,33.0,0.0,Yes,No
15,2026-04-16,East,Groceries,155.0,7.0,NaN,0.0,Yes,No
16,2026-04-17,East,Clothing,30.0,70.0,31.0,25.0,No,No
17,2026-04-18,East,Clothing,NaN,70.0,30.0,30.0,No,No
19,2026-04-20,East,Electronics,8.0,NaN,28.0,0.0,No,No
20,2026-04-21,West,Groceries,160.0,6.8,34.0,0.0,Yes,No
21,2026-04-22,West,Groceries,NaN,6.8,35.0,0.0,Yes,No
22,2026-04-23,West,Clothing,28.0,72.0,33.0,18.0,No,No
23,2026-04-24,West,Clothing,26.0,72.0,NaN,22.0,No,No
24,2026-04-25,West,Electronics,11.0,1080.0,30.0,0.0,NaN,No
25,2026-04-26,West,Electronics,10.0,1080.0,29.0,0.0,No,No
26,2026-04-27,West,Groceries,NaN,NaN,32.0,5.0,No,No
27,2026-04-28,North,Groceries,125.0,8.0,27.0,10.0,No,No
29,2026-04-30,East,Electronics,10.0,1100.0,27.0,0.0,No,No

In [81]:
df_no_na.groupby('rain_mm').agg({
    'units_sold': 'sum',
    'price': 'sum'
})

         units_sold   price
rain_mm
0.0           559.0  7945.1
2.0             0.0  1200.0
5.0             0.0    80.0
8.0            22.0    75.0
10.0          125.0     8.0
12.0           20.0    75.0
15.0          120.0     8.0
18.0           28.0    72.0
20.0          130.0     8.0
22.0           26.0    72.0
25.0           30.0    70.0
30.0            0.0    70.0

After dropping the NA values form the column rain_mm we still got that most units sold are from no raining days