# Read Write Excel and CSV Files
- skiprows lets you skip a row and create a header row for example

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("stock_data.csv")
df

,Datasource: Google finance,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,tickers,eps,revenue,price,people
1,GOOGL,27.82,87,845,larry page
2,WMT,4.61,484,65,n.a.
3,MSFT,-1,85,64,bill gates
4,RIL,not available,50,1023,mukesh ambani
5,TATA,5.6,-1,n.a.,ratan tata

In [3]:
df = pd.read_csv("stock_data.csv", skiprows=1)
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [4]:
df = pd.read_csv("stock_data.csv", header=1)
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [5]:
df = pd.read_csv("stock_data.csv", header=1, names = ["stock_symbol", "eps", 
                                                      "revenue", "price", "people"])
df

  stock_symbol            eps  revenue price         people
0        GOOGL          27.82       87   845     larry page
1          WMT           4.61      484    65           n.a.
2         MSFT             -1       85    64     bill gates
3         RIL   not available       50  1023  mukesh ambani
4         TATA            5.6       -1  n.a.     ratan tata

In [6]:
df = pd.read_csv("stock_data.csv", header=1, nrows=4)
df

  tickers            eps  revenue  price         people
0   GOOGL          27.82       87    845     larry page
1     WMT           4.61      484     65           n.a.
2    MSFT             -1       85     64     bill gates
3    RIL   not available       50   1023  mukesh ambani

In [7]:
df = pd.read_csv("stock_data.csv", header=1, na_values = {
    'eps': ['not available'],
    'revenue': [-1],
    'people': ['no available', 'n.a.']
})
df

  tickers    eps  revenue price         people
0   GOOGL  27.82     87.0   845     larry page
1     WMT   4.61    484.0    65            NaN
2    MSFT  -1.00     85.0    64     bill gates
3    RIL     NaN     50.0  1023  mukesh ambani
4    TATA   5.60      NaN  n.a.     ratan tata

In [8]:
df = pd.read_csv("stock_data.csv", header=1, na_values = ['not available', -1, 'n.a.'])
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT    NaN     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [9]:
df['pe'] = df['price']/df['eps']

In [10]:
df

  tickers    eps  revenue   price         people         pe
0   GOOGL  27.82     87.0   845.0     larry page  30.373832
1     WMT   4.61    484.0    65.0            NaN  14.099783
2    MSFT    NaN     85.0    64.0     bill gates        NaN
3    RIL     NaN     50.0  1023.0  mukesh ambani        NaN
4    TATA   5.60      NaN     NaN     ratan tata        NaN

In [11]:
df.to_csv("pe1.csv", index=False, header=False)

In [12]:
pip install openpyxl

Requirement already satisfied: openpyxl in /home/pedro-cella/Documents/Studies/Codebasics_Data_Science/env/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /home/pedro-cella/Documents/Studies/Codebasics_Data_Science/env/lib/python3.12/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [21]:
df_movies = pd.read_excel("movies_db.xlsx", "movies")
df_movies.head(4)

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5

In [22]:
df_financials = pd.read_excel("movies_db.xlsx", "financials")
df_financials.head(5)

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions       $$
3       104   180.0    854.0  Millions  Dollars
4       105   250.0    670.0  Millions      USD

In [23]:
def standardize_currency(curr):
    if curr == "$$" or curr == "Dollars":
        return "USD"
    return curr

df_financials = pd.read_excel("movies_db.xlsx", "financials", converters = {
    'currency': standardize_currency
})
df_financials.head(5)

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions      USD
3       104   180.0    854.0  Millions      USD
4       105   250.0    670.0  Millions      USD

In [27]:
df_merged = pd.merge(df_movies, df_financials, on="movie_id")
df_merged.head(4)

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,budget,revenue,unit,currency
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,1.0,12.5,Billions,INR
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,200.0,954.8,Millions,USD
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,165.0,644.8,Millions,USD
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5,180.0,854.0,Millions,USD

In [28]:
df_merged.to_excel("movies_merged.xlsx", sheet_name="merged", index=False)

In [29]:
df_stocks = pd.DataFrame({
    'tickers': ['GOOGL', 'WMT', 'MSFT'],
    'price': [845, 65, 64],
    'pe': [30.37, 14.26, 30.97],
    'eps': [27.82, 4.61, 2.12]
})
df_stocks

  tickers  price     pe    eps
0   GOOGL    845  30.37  27.82
1     WMT     65  14.26   4.61
2    MSFT     64  30.97   2.12

In [30]:
df_weather = pd.DataFrame({
    'day': ['1/1/2017', '1/2/2017', '1/3/2017'],
    'temperature': [32, 35, 28],
    'event': ['Rain', 'Sunny', 'Snow']
})
df_weather

        day  temperature  event
0  1/1/2017           32   Rain
1  1/2/2017           35  Sunny
2  1/3/2017           28   Snow

In [33]:
with pd.ExcelWriter("stocks_weather.xlsx") as writer:
    df_stocks.to_excel(writer, sheet_name="stocks")
    df_stocks.to_excel(writer, sheet_name="weather")