# Revision - Level 2 - 22/04/2026
- Revision about handling null/nan using .replace()

## ⚔️ MISSÃO 1 — Diagnóstico inteligente

Você recebeu um dataset onde existem valores como:

-99999, -88888, "no event", "N/A"

👉 Perguntas:
- Esses valores são dados reais ou erros?
- Como você identificaria automaticamente esses padrões?

👉 **Entrega:**
- Explicação + estratégia (pode usar pseudo-código)

I wouldn't think of this values as errors, the motive is that if multiple rows has this kind of value, then they shoul be put there on purpose, for example, some companies use -99999 to notify that is a null value instead of having **Null** or **NaN**, so first I would check if the values are repeated on multiple rows. Toautomatically check on this values I would use a code to list which rows they appear, and their sum. such as:

```python3
df.read_csv('example_table.csv')


```

In [9]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('../Module_9/Handle_NA_Values/weather_data-Copy1.csv')

# 1. Defina sua lista de valores esquisitos
valores_estranhos = [-99999, -88888, 'no event']

# 2. Filtre o DataFrame original apenas por esses valores
# Usamos .stack() para olhar todas as colunas de uma vez
df_estranhos = df[df.isin(valores_estranhos)]

# 3. Conte as ocorrências
resultado = df_estranhos.stack().value_counts().reset_index()
resultado.columns = ['Valor Esquisito', 'Total de Aparições']

print(resultado)

   Valor Esquisito  Total de Aparições
0         -99999.0                   8

## ⚔️ MISSÃO 2 — Replace estratégico

No dataset de clima (`weather_data`):

👉 Você deve:
- Substituir `-99999` e `-88888` por `NaN`
- Tratar o valor `"no event"`

👉 Perguntas:
- Você substituiria `"no event"` por `NaN` ou por `"Sunny"`?
- Em que cenário cada decisão faz sentido?

👉 **Entrega:**
- Decisão + justificativa

In [8]:
df2 = df.copy()
df2

         day  temperature  windspeed      event
0   1/1/2017         32.0        6.0       Rain
1   1/4/2017     -99999.0        9.0      Sunny
2   1/5/2017         28.0   -99999.0       Snow
3   1/6/2017     -99999.0        7.0   no event
4   1/7/2017         32.0   -99999.0       Rain
5   1/8/2017     -99999.0   -99999.0      Sunny
6   1/9/2017     -99999.0   -99999.0   no event
7  1/10/2017         34.1        8.1     Cloudy
8  1/11/2017         40.0       12.0      Sunny

In [11]:
df2 = df2.replace({
    -99999.0: np.nan,
    -88888.0: np.nan,
    r'^\s*no event\s*$': np.nan
}, regex=True)
df2

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

If we treat this as a real world dataset, I would change "no event" for NaN, because I don't want to interefere with the data without knowing its consequences as changing 'no event' for "Sunny" could cause.

## ⚔️ MISSÃO 3 — Transformação de dados (ESSENCIAL)

No dataset de comida (`food_db`):

👉 Você tem:
- `rating` (texto)
- `price` (string com `$`)
- `discount` (string com `%`)

👉 Perguntas:
- Quais dessas colunas deveriam virar numéricas?
- Qual o risco de NÃO converter?

👉 **Entrega:**
- Lista + explicação

I think it depends on its use, for me price should be in fact a numerical data type, because it's probably a great candidate for ana analysis, and the other columns depends on the context of the analysis, if an analysis needed the price after the discount, transforming the type from string to float, would be interesting and useful, the same way for rating, if we did ana analysis over mean(), or count() for example, having a numerical data type could be beneficial. So I think it depends on the analysis that would be done.

## ⚔️ MISSÃO 4 — Replace com impacto analítico

Você aplicou:

df.replace(['5%', '10%'], '13%')

👉 Perguntas:
- Isso altera o comportamento do negócio?
- Isso pode afetar análises futuras?

👉 Reflexão:
- Quando faz sentido padronizar valores?
- Quando NÃO faz sentido?

👉 **Entrega:**
- Análise crítica

This was a necessity over what as asked by the exercise, so making this replace was mandatory, but changing this on a real dataset, would not make any sense, only if the values fo 5% and 10% were wrong sou we would do a replace to correct it, but outside this scope woul not maki any sense on changing this values.