# Handle NA Values Part 2

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('weather_data-Copy1.csv')
df

         day  temperature  windspeed      event
0   1/1/2017         32.0        6.0       Rain
1   1/4/2017     -99999.0        9.0      Sunny
2   1/5/2017         28.0   -99999.0       Snow
3   1/6/2017     -99999.0        7.0   no event
4   1/7/2017         32.0   -99999.0       Rain
5   1/8/2017     -99999.0   -99999.0      Sunny
6   1/9/2017     -99999.0   -99999.0   no event
7  1/10/2017         34.1        8.1     Cloudy
8  1/11/2017         40.0       12.0      Sunny

In [8]:
import numpy as np
df.replace([-99999, -88888], value=np.nan)

         day  temperature  windspeed      event
0   1/1/2017         32.0        6.0       Rain
1   1/4/2017          NaN        9.0      Sunny
2   1/5/2017         28.0        NaN       Snow
3   1/6/2017          NaN        7.0   no event
4   1/7/2017         32.0        NaN       Rain
5   1/8/2017          NaN        NaN      Sunny
6   1/9/2017          NaN        NaN   no event
7  1/10/2017         34.1        8.1     Cloudy
8  1/11/2017         40.0       12.0      Sunny

In [9]:
df

         day  temperature  windspeed      event
0   1/1/2017         32.0        6.0       Rain
1   1/4/2017     -99999.0        9.0      Sunny
2   1/5/2017         28.0   -99999.0       Snow
3   1/6/2017     -99999.0        7.0   no event
4   1/7/2017         32.0   -99999.0       Rain
5   1/8/2017     -99999.0   -99999.0      Sunny
6   1/9/2017     -99999.0   -99999.0   no event
7  1/10/2017         34.1        8.1     Cloudy
8  1/11/2017         40.0       12.0      Sunny

In [14]:
df.replace({
    'temperature': -99999,
    'windspeed': [-99999, -88888],
    'event': r'^\s*no event\s*$'
}, np.nan, regex=True)

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [16]:
df.replace({
    -99999: np.nan,
    -88888: np.nan,
    r'^\s*no event\s*$': 'Sunny'
}, regex=True)

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0   Sunny
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN   Sunny
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [17]:
df = pd.DataFrame({
    'score': ['exceptional', 'average', 'good', 'poor', 'average', 'exceptional'],
    'student': ['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica']
})
df

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [18]:
df.replace(['poor', 'average', 'good', 'exceptional'], [1,2,3,4])

  score  student
0     4      rob
1     2     maya
2     3  parthiv
3     1      tom
4     2   julian
5     4    erica

## Takeaways
- The **df.replace function** allows a variety of options to handle missing values and replace them.
- You don't have to remember all the functions or parameters, **just understand their uses.** While solving any problem, use your best friends **Mr. G** and **Mr. C** to figure out which functions and parameters to use in the code.