# Revision - Level 2 - Create/Write and Read CSV/Excel files

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("final_movie_data.csv")
df.head(5)

,movie_id,title,budget,revenue,year_classify
0,101,K.G.F: Chapter 2,1.0,12.5,From 2000
1,102,Doctor Strange in the Multiverse of Madness,200.0,954.8,From 2000
2,103,Thor: The Dark World,165.0,644.8,From 2000
3,104,Thor: Ragnarok,180.0,854.0,From 2000
4,105,Thor: Love and Thunder,250.0,670.0,From 2000

## 1. Criar coluna de lucro

Crie uma nova coluna chamada:

`profit`

Onde:

`profit` = `revenue` - `budget`

Depois mostre:

as 5 primeiras linhas com `title`, `budget`, `revenue` e `profit`

In [4]:
df['profit'] = df['revenue'] - df['budget']
df.head(5)

,movie_id,title,budget,revenue,year_classify,profit
0,101,K.G.F: Chapter 2,1.0,12.5,From 2000,11.5
1,102,Doctor Strange in the Multiverse of Madness,200.0,954.8,From 2000,754.8
2,103,Thor: The Dark World,165.0,644.8,From 2000,479.8
3,104,Thor: Ragnarok,180.0,854.0,From 2000,674.0
4,105,Thor: Love and Thunder,250.0,670.0,From 2000,420.0

## 2. Filmes lucrativos

Filtre apenas os filmes com:

`profit > 0` 

Depois responda:

quantos filmes deram lucro?

In [13]:
df.shape

(37, 6)

In [35]:
(df['profit'] > 0).sum()
# After the analysis all movies inserted into the dataframe are profitable movies

np.int64(37)

## 3. Filmes com prejuízo ou lucro baixo

Encontre os filmes com:

`profit <= 0`

Se não houver nenhum, encontre os 5 com menor lucro.

In [15]:
df[df.profit <= 0]

Empty DataFrame
Columns: [movie_id, title, budget, revenue, year_classify, profit]
Index: []

In [16]:
df.nsmallest(5, 'profit')

    movie_id                      title  budget  revenue year_classify  profit
10       118      It's a Wonderful Life    3.18      3.3   before 2000    0.12
31       139                     Race 3    1.80      3.1     From 2000    1.30
34       132  Pushpa: The Rise - Part 1    2.00      3.6     From 2000    1.60
24       110           Bajirao Mastani     1.40      3.5     From 2000    2.10
36       134   Baahubali: The Beginning    1.80      6.5     From 2000    4.70

## 4. Top 5 maiores receitas

Mostre os 5 filmes com maior valor de:

`revenue`

Depois compare:

eles também estão entre os de maior lucro?

In [20]:
df_largest_revenue = df.nlargest(5, 'revenue')
df_largest_revenue

    movie_id              title   budget   revenue year_classify   profit
33       127    Pather Panchali  70000.0  100000.0   before 2000  30000.0
30       136  Bajrangi Bhaijaan    900.0   11690.0     From 2000  10790.0
27       130                 PK    850.0    8540.0     From 2000   7690.0
22       108           3 Idiots    550.0    4000.0     From 2000   3450.0
29       135  The Kashmir Files    250.0    3409.0     From 2000   3159.0

In [21]:
df_largest_profit = df.nlargest(5, 'profit')
df_largest_profit

    movie_id              title   budget   revenue year_classify   profit
33       127    Pather Panchali  70000.0  100000.0   before 2000  30000.0
30       136  Bajrangi Bhaijaan    900.0   11690.0     From 2000  10790.0
27       130                 PK    850.0    8540.0     From 2000   7690.0
22       108           3 Idiots    550.0    4000.0     From 2000   3450.0
29       135  The Kashmir Files    250.0    3409.0     From 2000   3159.0

In [24]:
diff = df_largest_revenue.compare(df_largest_profit)
print(diff)

Empty DataFrame
Columns: []
Index: []

About the question, in this case the top 5 movies with the largest revenue are the top 5 movies with the largest profit as well

## 5. Top 5 maiores lucros

Mostre os 5 filmes com maior:

`profit`

Depois responda:

maior receita e maior lucro são sempre a mesma coisa?

In [26]:
df.nlargest(5, 'profit')

    movie_id              title   budget   revenue year_classify   profit
33       127    Pather Panchali  70000.0  100000.0   before 2000  30000.0
30       136  Bajrangi Bhaijaan    900.0   11690.0     From 2000  10790.0
27       130                 PK    850.0    8540.0     From 2000   7690.0
22       108           3 Idiots    550.0    4000.0     From 2000   3450.0
29       135  The Kashmir Files    250.0    3409.0     From 2000   3159.0

About the question, no revenue and profit are not always the same thing. When talking about movies or the success of a movie, you must think about 3 variables: budget, revenue and profit. Budget is how much a movie cost to be made, Revenue usually means how much a movie could pay itself, that's why in some cases there are minimal revenue costs that must be targeted, and profit is about how much of revenue we have made over the amount we needed to make the movie. Basically budget means the cost of the movie, revenue means the money that pays the movie, and profit is the amount gain beyond the cost of the movie.

## 6. Análise por faixa de ano

Agrupe por:

`year_classify`

E calcule:

- média de budget
- média de revenue
- média de profit
- quantidade de filmes

In [29]:
df.groupby('year_classify').agg({
    'budget': 'mean',
    'revenue': 'mean',
    'profit': 'mean',
    'title': 'count'
})

                    budget       revenue       profit  title
year_classify
From 2000       221.506897   1599.868966  1378.362069     29
before 2000    8840.047500  13242.225000  4402.177500      8

## 7. Filtro inteligente

Encontre filmes que tenham ao mesmo tempo:

- budget acima da média
- revenue acima da média

Depois responda:

quantos filmes estão nesse grupo?

In [30]:
df[(df.budget > df['budget'].mean()) & (df['revenue'] > df.revenue.mean())]

    movie_id            title   budget   revenue year_classify   profit
33       127  Pather Panchali  70000.0  100000.0   before 2000  30000.0

Only one movie is beyon the mean in both revenue and profit

## 8. Eficiência financeira

Crie uma nova coluna chamada algo como:

`roi`
ou
`return_ratio`

Onde tu vai comparar retorno em relação ao orçamento.

A ideia é descobrir:

- quais filmes foram mais eficientes financeiramente

Depois mostre os 5 melhores.

In [33]:
df['roi'] = (((df['revenue'] - df['budget'])/df['budget'])*100).round(2)
df.head(5)

,movie_id,title,budget,revenue,year_classify,profit,roi
0,101,K.G.F: Chapter 2,1.0,12.5,From 2000,11.5,1150.00
1,102,Doctor Strange in the Multiverse of Madness,200.0,954.8,From 2000,754.8,377.40
2,103,Thor: The Dark World,165.0,644.8,From 2000,479.8,290.79
3,104,Thor: Ragnarok,180.0,854.0,From 2000,674.0,374.44
4,105,Thor: Love and Thunder,250.0,670.0,From 2000,420.0,168.00

A princípio todos foram eficientes, visto que todos tiveram ROI positivo.