# Concat and Merge
- `.merge()` works as an SQL JOIN
- `.concat()` concatenate DataFrames **vertically(rows)** or **horizontally(columns)**
- `.merge()` combine DataFrames **based on matching values** in one or more columns (like SQL joins).

In [1]:
import pandas as pd

In [2]:
india_weather = pd.DataFrame({
    "city": ["mumbai", "delhi", "banglore"],
    "temperature": [32, 45, 30],
    "humidity": [80, 60, 78]
})
india_weather

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78

In [4]:
us_weather = pd.DataFrame({
    "city": ["new york", "chicago", "orlando"],
    "temperature": [21, 14, 35],
    "humidity": [68, 65, 75]
})
us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [5]:
df = pd.concat([india_weather, us_weather])
df

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [6]:
df = pd.concat([india_weather, us_weather], ignore_index=True)
df

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
3  new york           21        68
4   chicago           14        65
5   orlando           35        75

In [8]:
df = pd.concat([india_weather, us_weather], keys=["india", "us"])
df

             city  temperature  humidity
india 0    mumbai           32        80
      1     delhi           45        60
      2  banglore           30        78
us    0  new york           21        68
      1   chicago           14        65
      2   orlando           35        75

In [10]:
df.loc['india']

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78

In [11]:
temperature_df = pd.DataFrame({
    "city": ["mumbai", "delhi", "banglore"],
    "temperature": [32, 45, 30]
}, index=[0,1,2])
temperature_df

       city  temperature
0    mumbai           32
1     delhi           45
2  banglore           30

In [14]:
windspeed_df = pd.DataFrame({
    "city": ["delhi", "banglore"],
    "temperature": [7, 12]
}, index=[1,0])
windspeed_df

       city  temperature
1     delhi            7
0  banglore           12

In [16]:
pd.concat([temperature_df, windspeed_df], axis=1)

       city  temperature      city  temperature
0    mumbai           32  banglore         12.0
1     delhi           45     delhi          7.0
2  banglore           30       NaN          NaN

In [17]:
df1 = pd.DataFrame({
    "city": ["new york", "chicago", "orlando"],
    "temperature": [21, 14, 35],
})
df1

       city  temperature
0  new york           21
1   chicago           14
2   orlando           35

In [19]:
df2 = pd.DataFrame({
    "city": ["chicago", "new york", "orlando"],
    "humidity": [65, 68, 75],
})
df2

       city  humidity
0   chicago        65
1  new york        68
2   orlando        75

In [20]:
df3 = pd.merge(df1, df2, on="city")
df3

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [24]:
df1 = pd.DataFrame({
    "city": ["new york", "chicago", "orlando", "baltimore"],
    "temperature": [21, 14, 35, 38],
})
df1

        city  temperature
0   new york           21
1    chicago           14
2    orlando           35
3  baltimore           38

In [25]:
df2 = pd.DataFrame({
    "city": ["chicago", "new york", "san diego"],
    "humidity": [65, 68, 71],
})
df2

        city  humidity
0    chicago        65
1   new york        68
2  san diego        71

In [28]:
pd.merge(df1, df2, on="city", how="inner")

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65

In [29]:
pd.merge(df1, df2, on="city", how="left")

        city  temperature  humidity
0   new york           21      68.0
1    chicago           14      65.0
2    orlando           35       NaN
3  baltimore           38       NaN

In [30]:
pd.merge(df1, df2, on="city", how="right")

        city  temperature  humidity
0    chicago         14.0        65
1   new york         21.0        68
2  san diego          NaN        71

In [31]:
pd.merge(df1, df2, on="city", how="outer")

        city  temperature  humidity
0  baltimore         38.0       NaN
1    chicago         14.0      65.0
2   new york         21.0      68.0
3    orlando         35.0       NaN
4  san diego          NaN      71.0